config/routes.rb
Rails.application.routes.draw do

  concern :sluggable do
    collection do
      get 'slug'
    end
  end

  namespace :api, defaults: {format: :json} do
    scope path: '/discourse_integration', as: :discourse do
      get 'top_menu', to: 'discourse_integration#top_menu', as: :top_menu
    end
  end

  resources :resorts, path: 'estacoes-ski-snowboard', concerns: :sluggable, except: :show
  get '/resorts/:id', to: 'resorts#resort_redirect', as: :resort_redirect
  get 'estacoes-ski-snowboard/:resort_category_id/:id', to: 'resorts#show', as: :show_resort

  get 'estacoes-ski-snowboard/:id', to: 'resort_categories#show', as: :show_resort_category
  resources :resort_categories, concerns: :sluggable, except: :show

  get '/resorts', to: redirect('/estacoes-ski-snowboard')
  get '/resort_categories/:id', to: redirect('/estacoes-ski-snowboard/%{id}')

  resources :tips, path: 'dicas', concerns: :sluggable, except: :show
  get '/tips/:id', to: 'tips#tip_redirect', as: :tip_redirect
  get 'dicas/:category_id/:id', to: 'tips#show', as: :show_tip

  get 'dicas/:id', to: 'tip_categories#show', as: :show_tip_category
  resources :tip_categories, concerns: :sluggable, except: :show

  get '/tips', to: redirect('/dicas')
  get '/tip_categories/:id', to: redirect('/dicas/%{id}')

  resources :videos, concerns: :sluggable, except: :show
  get 'videos/:category_id/:id', to: 'videos#show', as: :show_video

  get 'videos/:id', to: 'video_categories#show', as: :show_video_category
  resources :video_categories, concerns: :sluggable, except: :show

  resources :breezes, :breeze_categories
  resources :image_galleries, :media_image_categories

  resources :accommodations, :tour_styles
  resources :offers do
    get 'search', on: :collection
  end
  resources :tours, path: '/vamo-junto-snowboard' do
    get 'search', on: :collection
    post 'comment', on: :member
    scope module: 'tours' do
      resources :participants do
        get 'recall', on: :member
      end
    end
  end
  resources :offers, path: '/pacotes-snowboard' do
    scope module: 'offers' do
      resources :participants
    end
  end

  ActiveAdmin.routes(self)

  root 'static_pages#index'

  get '/galera', to: 'static_pages#galera', path: '/contatos'
  get '/friends', to: 'static_pages#friends', path: '/amigos'

  get 'users_controller/finish_signup'

  get '/discourse/sso', to: 'discourse#sso'
  get '/discourse/after_sign_in', to: 'discourse#after_sign_in'
  get '/discourse/logout', to: 'discourse#logout'

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    scope module: 'users' do
      resources :tours
      resources :offers
    end
  end
  scope '/manage' do
    resources :users do
      resources :image_galleries
      resources :notifications
      patch 'update_password', on: :collection
      resources :tours, module: 'manage'
    end
  end
  namespace :manage do
    resources :tours do
      scope module: 'tours' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end
    resources :offers do
      scope module: 'offers' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end
  end

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/user' => 'users#profile', via: [:get], :as => :profile
  match '/user/full_sign_out' => 'users#full_sign_out', via: [:get], :as => :full_sign_out
  match '/athletes' => 'users#athletes', via: [:get], :as => :athletes, path: 'atletas-de-snowboard'
  match '/agencies' => 'users#agencies', via: [:get], :as => :agencies, path: 'agencias-ski-snowboard'
  match '/organizations' => 'users#organizations', via: [:get], :as => :organizations, path: 'ogranizacoes-de-snowboard'

  mount Forem::Engine, :at => '/forum', :as => 'forem'

  get '/galera', to: redirect('contatos')
  get '/friends', to: redirect('amigos')
  get '/tours', to: redirect('vamo-junto-snowboard')
  get '/athletes', to: redirect('atletas-de-snowboard')
  get '/agencies', to: redirect('agencias-ski-snowboard')
  get '/organizations', to: redirect('ogranizacoes-de-snowboard')

end

app/views/shared/_image_gallery_form.html.haml
%h3 Gallery
%ul
-unless media.gallery_images.all.count.zero?
  %table
    -media.gallery_images.all.each do |image|
      %tr
        %td{style: "padding: 10px;"}
          = image_tag image.image_url(:thumb).to_s
        %td
          = text_field_tag "gallery_images[name][#{image.id}]", image.name, {placeholder: 'Titulo'}
        %td
          = text_area_tag "gallery_images[description][#{image.id}]", image.description, {placeholder: 'Descricao',size: '30x5'}
        %td{style: "padding: 10px;"}
          Substituir img?
          %br
          = file_field '', "gallery_images[update_images][#{image.id}]"
        %td
          Deletar?
          %br
          = check_box_tag "gallery_images[remove_image][#{image.id}]"
.field
  = f.label :add_gallery_images
  = f.file_field :add_gallery_images, :multiple => true, name: 'gallery_images[images][]'

app/views/shared/_image_gallery_form_tips.html.haml
%h3 Gallery
%ul
-unless media.gallery_images.all.count.zero?
  %table
    -media.gallery_images.all.each do |image|
      %tr
        %td
          Ordem
          %br
          = text_field_tag "gallery_images[order][#{image.id}]", image.order, {placeholder: 'order', class: "order"}
        %td
          = image_tag image.image_url(:thumb).to_s
        %td
          = text_field_tag "gallery_images[name][#{image.id}]", image.name, {placeholder: 'Titulo'}
          = text_field_tag "gallery_images[url][#{image.id}]", image.url, {placeholder: 'url', style: "display: block;"}
        %td
          = text_area_tag "gallery_images[description][#{image.id}]", image.description, {placeholder: 'Descricao',size: '30x5'}
        %td
          Substituir img?
          %br
          = file_field '', "gallery_images[update_images][#{image.id}]"
        %td
          Deletar?
          %br
          = check_box_tag "gallery_images[remove_image][#{image.id}]"
.field
  = f.label :add_gallery_images
  = f.file_field :add_gallery_images, :multiple => true, name: 'gallery_images[images][]'

app/views/shared/_links.haml
- if Devise.mappings[:user].recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to t('forgotPsw'), new_password_path(:user)
  %br/
- if Devise.mappings[:user].confirmable? && controller_name != 'confirmations'
  = link_to t('noConfirm'), new_confirmation_path(:user)
  %br/
- if Devise.mappings[:user].lockable? && User.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to t('noUnlock'), new_unlock_path(:user)
  %br/
.buttons
  - if Devise.mappings[:user].omniauthable?
    - User.omniauth_providers.each do |provider|
      -#
        %b= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(:user, provider)
      %a.button{:href => omniauth_authorize_path(:user, provider)}, "Sign in with #{provider.to_s.titleize}"
      -# %br/
.clear

app/views/shared/_sign_in.html.haml
#signIn{:title => t('signIn')}
  = form_for(User.new, url: session_path(:user),       |
    html:{id: 'sign_in_user', :'data-type' => 'json'}, |
    remote: true) do |f|                               |
    = f.email_field :email, :autofocus => true, :placeholder => 'email'
    %p
    = f.password_field :password, :placeholder => 'password'
    %p
    - if Devise.mappings[:user].rememberable?
      %label.checkbox
        = f.check_box :remember_me
        \ Remember_me
    = f.submit "Sign in", :class => "btn btn-success"
  .modal-footer

app/views/shared/_sign_up.html.haml
#sign_up.modal.hide.fade.in
  .modal-header
    %button.close{"data-dismiss" => "modal"} x
    %h1 Sign up
  .modal-body
    = form_for(User.new, url: registration_path(:user),                        |
      html: {id: 'sign_up_user', :'data-type' => 'json'}, remote: true) do |f| |
      %div
      = f.label :email
      = f.email_field :email, autofocus: true
      %div
      = f.label :password
      = f.password_field :password, autocomplete: "off"
      %div
      = f.label :password_confirmation
      = f.password_field :password_confirmation, autocomplete: "off"
      %div= f.submit "Sign up"
  .modal-footer