config/routes.rb
Rails.application.routes.draw do

  concern :sluggable do
    collection do
      get 'slug'
    end
  end

  namespace :api, defaults: {format: :json} do
    scope path: '/discourse_integration', as: :discourse do
      get 'top_menu', to: 'discourse_integration#top_menu', as: :top_menu
    end
  end

  resources :resorts, path: 'estacoes-ski-snowboard', concerns: :sluggable, except: :show
  get '/resorts/:id', to: 'resorts#resort_redirect', as: :resort_redirect
  get 'estacoes-ski-snowboard/:resort_category_id/:id', to: 'resorts#show', as: :show_resort

  get 'estacoes-ski-snowboard/:id', to: 'resort_categories#show', as: :show_resort_category
  resources :resort_categories, concerns: :sluggable, except: :show

  get '/resorts', to: redirect('/estacoes-ski-snowboard')
  get '/resort_categories/:id', to: redirect('/estacoes-ski-snowboard/%{id}')

  resources :tips, path: 'dicas', concerns: :sluggable, except: :show
  get '/tips/:id', to: 'tips#tip_redirect', as: :tip_redirect
  get 'dicas/:category_id/:id', to: 'tips#show', as: :show_tip

  get 'dicas/:id', to: 'tip_categories#show', as: :show_tip_category
  resources :tip_categories, concerns: :sluggable, except: :show

  get '/tips', to: redirect('/dicas')
  get '/tip_categories/:id', to: redirect('/dicas/%{id}')

  resources :videos, concerns: :sluggable, except: :show
  get 'videos/:category_id/:id', to: 'videos#show', as: :show_video

  get 'videos/:id', to: 'video_categories#show', as: :show_video_category
  resources :video_categories, concerns: :sluggable, except: :show

  resources :breezes, :breeze_categories
  resources :image_galleries, :media_image_categories

  resources :accommodations, :tour_styles
  resources :offers do
    get 'search', on: :collection
  end
  resources :tours, path: '/vamo-junto-snowboard' do
    get 'search', on: :collection
    post 'comment', on: :member
    scope module: 'tours' do
      resources :participants do
        get 'recall', on: :member
      end
    end
  end
  resources :offers, path: '/pacotes-snowboard' do
    scope module: 'offers' do
      resources :participants
    end
  end

  ActiveAdmin.routes(self)

  root 'static_pages#index'

  get '/galera', to: 'static_pages#galera', path: '/contatos'
  get '/friends', to: 'static_pages#friends', path: '/amigos'

  get 'users_controller/finish_signup'

  get '/discourse/sso', to: 'discourse#sso'
  get '/discourse/after_sign_in', to: 'discourse#after_sign_in'
  get '/discourse/logout', to: 'discourse#logout'

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    scope module: 'users' do
      resources :tours
      resources :offers
    end
  end
  scope '/manage' do
    resources :users do
      resources :image_galleries
      resources :notifications
      patch 'update_password', on: :collection
      resources :tours, module: 'manage'
    end
  end
  namespace :manage do
    resources :tours do
      scope module: 'tours' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end
    resources :offers do
      scope module: 'offers' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end
  end

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/user' => 'users#profile', via: [:get], :as => :profile
  match '/user/full_sign_out' => 'users#full_sign_out', via: [:get], :as => :full_sign_out
  match '/athletes' => 'users#athletes', via: [:get], :as => :athletes, path: 'atletas-de-snowboard'
  match '/agencies' => 'users#agencies', via: [:get], :as => :agencies, path: 'agencias-ski-snowboard'
  match '/organizations' => 'users#organizations', via: [:get], :as => :organizations, path: 'ogranizacoes-de-snowboard'

  mount Forem::Engine, :at => '/forum', :as => 'forem'

  get '/galera', to: redirect('contatos')
  get '/friends', to: redirect('amigos')
  get '/tours', to: redirect('vamo-junto-snowboard')
  get '/athletes', to: redirect('atletas-de-snowboard')
  get '/agencies', to: redirect('agencias-ski-snowboard')
  get '/organizations', to: redirect('ogranizacoes-de-snowboard')

end

app/models/resort_category.rb
# create_table :resort_categories, force: true do |t|
#   t.string  :name
#   t.text    :description
#   t.string  :ancestry
#   t.string  :index
#   t.integer :ancestry_depth, default: 0
#   t.string  :image
#   t.string  :slug
# end

class ResortCategory < ActiveRecord::Base
  include Slug
  slugged :name

  has_ancestry( :cache_depth => true )

  has_many :resorts
  validates :name, presence: true
  mount_uploader :image, CategoryImageUploader

end

app/controllers/resort_categories_controller.rb
class ResortCategoriesController < ApplicationController
  load_and_authorize_resource

  # GET /resort_categories
  # GET /resort_categories.json
  def index
    @resort_categories = ResortCategory.all
  end

  # GET /resort_categories/1
  # GET /resort_categories/1.json
  def show
    @resorts = @resort_category.resorts.page(params[:page])
  end

  # GET /resort_categories/new
  def new
    @resort_category = ResortCategory.new
  end

  # GET /resort_categories/1/edit
  def edit
  end

  def slug
    resort_category = ResortCategory.new name: params[:title]
    render json: { slug: resort_category.slug_preview }
  end

  # POST /resort_categories
  # POST /resort_categories.json
  def create
    @resort_category = ResortCategory.new(resort_category_params)

    respond_to do |format|
      if @resort_category.save
        format.html { redirect_to show_resort_category_path(@resort_category), notice: 'Resort category was successfully created.' }
        format.json { render :show, status: :created, location: @resort_category }
      else
        format.html { render :new }
        format.json { render json: @resort_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resort_categories/1
  # PATCH/PUT /resort_categories/1.json
  def update
    respond_to do |format|
      if @resort_category.update(resort_category_params)
        format.html { redirect_to show_resort_category_path(@resort_category), notice: 'Resort category was successfully updated.' }
        format.json { render :show, status: :ok, location: @resort_category }
      else
        format.html { render :edit }
        format.json { render json: @resort_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resort_categories/1
  # DELETE /resort_categories/1.json
  def destroy
    @resort_category.destroy
    respond_to do |format|
      format.html { redirect_to resort_categories_url, notice: 'Resort category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def resort_category_params
    params.require(:resort_category).permit(:name, :slug, :parent_id, :description, :image)
  end
end

app/helpers/resort_categories_helper.rb
module ResortCategoriesHelper
  def nested_resort_categories(resort_categories)
    resort_categories.map do |resort_category, sub_resort_category|
      render(resort_category) + content_tag(:ul, nested_resort_categories(sub_resort_category), :class=> 'sub_resort_category')
    end.join.html_safe
  end

  def menu_resort_categories(resort_categories)
    resort_categories.map do |resort_category, sub_resort_category|
    if sub_resort_category.empty?
      content_tag(:li, link_to(resort_category.name, show_resort_category_path(resort_category)))
    else
      content_tag(:li, link_to(resort_category.name, show_resort_category_path(resort_category)) + content_tag(:ul, sub_menu_resort_categories(sub_resort_category),:class => 'subsubmenu'),:class => 'subsubmenu-item' )
    end

    end.join.html_safe
  end

  def sub_menu_resort_categories(resort_categories)
    resort_categories.map do |resort_category, sub_resort_category|
      content_tag(:li,link_to(resort_category.name, show_resort_category_path(resort_category)))
    end.join.html_safe
  end

  def aside_resort_categories(resort_category)
    html = ''
    resort_category.path.from_depth(0).each do |parent|
      if parent.depth == resort_category.depth
        html += link_to parent.name, show_resort_category_path(parent), :class => :active
      else
        html += link_to parent.name, show_resort_category_path(parent)
      end
      if parent.depth < resort_category.depth
        html +=content_tag(:span, ' >> ')
      end
    end
    html.html_safe
  end

end

app/views/resort_categories/_form.html.haml
= form_for @resort_category do |f|
  - if @resort_category.errors.any?
    #error_explanation
      %h1= "#{pluralize(@resort_category.errors.count, "error")} prohibited this resort_category from being saved:"
      %ul
        - @resort_category.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name, data: { url: slug_resort_categories_path }
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :parent_id, t('parent')
    = f.collection_select(:parent_id, ResortCategory.all,:id, :name,{:prompt => t('selectParent')})
  .field
    = f.label :description
    = f.text_area :description,:class => 'froala', :rows => 40, :cols => 120
  .field
    = image_tag @resort_category.image_url(:thumb_1200_630).to_s
    = f.label :image
    = f.file_field :image
    = f.check_box :remove_image

  .actions
    = f.submit 'Save'

app/views/resort_categories/_resort_category.html.haml
%li.resort_category
  .details
    %p.name= resort_category.name
    %p= truncate( resort_category.description, length: 200)
  .clear
  - if can? :resort_category, :update, :destroy
    .control
      = link_to t('edit'), edit_resort_category_path(resort_category)
      = link_to 'Destroy', resort_category, method: :delete, data: { confirm: 'Are you sure?' }

app/views/resort_categories/edit.html.haml
%h2 Editing resort_category

= render 'form'

= link_to 'Show', @resort_category
\|
= link_to 'Back', resort_categories_path

app/views/resort_categories/index.html.haml
.main-content
  .heading
  -if can? ResortCategory, :create
    = link_to 'New Resort category', new_resort_category_path
  .clear
  %ul.resort_category_list
    =nested_resort_categories @resort_categories.arrange
.clear

app/views/resort_categories/new.html.haml
%h1=t('newResortCategory')

= render 'form'

= link_to 'Back', resort_categories_path

app/views/resort_categories/show.html.haml
%p#notice= notice
.main-content{:itemscope => true, :itemtype => "http://schema.org/Article"}
  -content_for :for_head do
    /* general METAS
    %title Zona Radical | Estações de Snowboard: #{@resort_category.name}
    %meta{:name => "description", :content =>  strip_tags(@resort_category.description.to_s)}
    /* facebook METAS
    %meta{:property=>"og:type", :content =>"article"}
    %meta{:property=>"og:title", :content =>  t('resorts') + ': ' + @resort_category.name + " | Zona Radical"}
    %meta{:property=>"og:description", :content =>  strip_tags(@resort_category.description.to_s)}
    %meta{:property=>"og:url", :content => request.original_url.to_s}
    /* @Todo Make proper images for all resort categories
    %meta{:property=> "og:image", :content=> @resort_category.image_url(:thumb_1200_630).to_s}
    /* schema.org METAS
    %meta{:itemprop=>"author", :content =>"Zona Radical"}
    %meta{:itemprop=>"url", :content => request.original_url.to_s}
  .heading
    %h1= t('resorts') + ': ' + @resort_category.name
    %meta{:itemprop=>"name", :content => t('resorts') + ': ' + @resort_category.name + " | Zona Radical"}
    .fb-like{"data-href"=> request.original_url.to_s, "data-layout"=>"button", "data-action"=>"like", "data-show-faces"=>"true", "data-share"=>"true", :style => "float: right;"}
  .introtext{:itemprop=>"description"}
    = @resort_category.description.html_safe unless @resort_category.description.nil?
  -if can? :update, @resort_category
    = link_to t('edit'), edit_resort_category_path(@resort_category)
  .clear
  %ul.stations-list
    =render @resorts
    = will_paginate @resorts,:previous_label => '<<',:next_label => '>>', :inner_window => 1
  -if @resort_category.children?
    -@resort_category.children.each do |resort_category|
      -unless resort_category.resorts.empty?
        .heading
          %h1= resort_category.name + ' (' + resort_category.resorts.size.to_s + ')'
          = link_to t('allResorts') + resort_category.name, show_resort_category_path(resort_category), class: :all
        .introtext
          -if !resort_category.description.nil?
            =truncate_html(resort_category.description, length: 203, omission: '...')
            -if resort_category.description.html_safe.length>200
              =link_to t('readMore'), show_resort_category_path(resort_category)
        -if can? :update, resort_category
          = link_to t('edit'), edit_resort_category_path(resort_category)
        .clear
        %ul.stations-list
          =render resort_category.resorts.limit(3)
          -if resort_category.resorts.size > 3
            %p.others= link_to t('otherResorts') + resort_category.name, show_resort_category_path(resort_category)
-content_for :aside do
  %aside
    =render 'shared/aside/aside_social_buttons'
    =render 'shared/aside/aside_resort_category', :resort_category => @resort_category
    =render 'shared/aside/aside_fb_like_box'
    =render 'shared/aside/aside_advert'
    =render 'shared/aside/aside_resort_gallery'
  .clear