config/routes.rb
Rails.application.routes.draw do

  concern :sluggable do
    collection do
      get 'slug'
    end
  end

  namespace :api, defaults: {format: :json} do
    scope path: '/discourse_integration', as: :discourse do
      get 'top_menu', to: 'discourse_integration#top_menu', as: :top_menu
    end
  end

  resources :resorts, path: 'estacoes-ski-snowboard', concerns: :sluggable, except: :show
  get '/resorts/:id', to: 'resorts#resort_redirect', as: :resort_redirect
  get 'estacoes-ski-snowboard/:resort_category_id/:id', to: 'resorts#show', as: :show_resort

  get 'estacoes-ski-snowboard/:id', to: 'resort_categories#show', as: :show_resort_category
  resources :resort_categories, concerns: :sluggable, except: :show

  get '/resorts', to: redirect('/estacoes-ski-snowboard')
  get '/resort_categories/:id', to: redirect('/estacoes-ski-snowboard/%{id}')

  resources :tips, path: 'dicas', concerns: :sluggable, except: :show
  get '/tips/:id', to: 'tips#tip_redirect', as: :tip_redirect
  get 'dicas/:category_id/:id', to: 'tips#show', as: :show_tip

  get 'dicas/:id', to: 'tip_categories#show', as: :show_tip_category
  resources :tip_categories, concerns: :sluggable, except: :show

  get '/tips', to: redirect('/dicas')
  get '/tip_categories/:id', to: redirect('/dicas/%{id}')

  resources :videos, concerns: :sluggable, except: :show
  get 'videos/:category_id/:id', to: 'videos#show', as: :show_video

  get 'videos/:id', to: 'video_categories#show', as: :show_video_category
  resources :video_categories, concerns: :sluggable, except: :show

  resources :breezes, :breeze_categories
  resources :image_galleries, :media_image_categories

  resources :accommodations, :tour_styles
  resources :offers do
    get 'search', on: :collection
  end
  resources :tours, path: '/vamo-junto-snowboard' do
    get 'search', on: :collection
    post 'comment', on: :member
    scope module: 'tours' do
      resources :participants do
        get 'recall', on: :member
      end
    end
  end
  resources :offers, path: '/pacotes-snowboard' do
    scope module: 'offers' do
      resources :participants
    end
  end

  ActiveAdmin.routes(self)

  root 'static_pages#index'

  get '/galera', to: 'static_pages#galera', path: '/contatos'
  get '/friends', to: 'static_pages#friends', path: '/amigos'

  get 'users_controller/finish_signup'

  get '/discourse/sso', to: 'discourse#sso'
  get '/discourse/after_sign_in', to: 'discourse#after_sign_in'
  get '/discourse/logout', to: 'discourse#logout'

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    scope module: 'users' do
      resources :tours
      resources :offers
    end
  end
  scope '/manage' do
    resources :users do
      resources :image_galleries
      resources :notifications
      patch 'update_password', on: :collection
      resources :tours, module: 'manage'
    end
  end
  namespace :manage do
    resources :tours do
      scope module: 'tours' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end
    resources :offers do
      scope module: 'offers' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end
  end

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/user' => 'users#profile', via: [:get], :as => :profile
  match '/user/full_sign_out' => 'users#full_sign_out', via: [:get], :as => :full_sign_out
  match '/athletes' => 'users#athletes', via: [:get], :as => :athletes, path: 'atletas-de-snowboard'
  match '/agencies' => 'users#agencies', via: [:get], :as => :agencies, path: 'agencias-ski-snowboard'
  match '/organizations' => 'users#organizations', via: [:get], :as => :organizations, path: 'ogranizacoes-de-snowboard'

  mount Forem::Engine, :at => '/forum', :as => 'forem'

  get '/galera', to: redirect('contatos')
  get '/friends', to: redirect('amigos')
  get '/tours', to: redirect('vamo-junto-snowboard')
  get '/athletes', to: redirect('atletas-de-snowboard')
  get '/agencies', to: redirect('agencias-ski-snowboard')
  get '/organizations', to: redirect('ogranizacoes-de-snowboard')

end

app/models/tip_category.rb
# create_table :tip_categories, force: true do |t|
#   t.string   :name
#   t.text     :description
#   t.string   :index
#   t.datetime :created_at
#   t.datetime :updated_at
#   t.string   :image
#   t.string   :slug
#   t.integer  :ancestry_depth, default: 0
# end

class TipCategory < ActiveRecord::Base
  include Slug
  slugged :name

  has_many :tips
  validates :name, presence: true
  mount_uploader :image, CategoryImageUploader
end

app/controllers/tip_categories_controller.rb
class TipCategoriesController < ApplicationController
  load_and_authorize_resource

  # GET /tip_categories
  # GET /tip_categories.json
  def index
    @tip_categories = TipCategory.all
  end

  # GET /tip_categories/1
  # GET /tip_categories/1.json
  def show
    @tips = @tip_category.tips.page(params[:page])
  end

  # GET /tip_categories/new
  def new
    @tip_category = TipCategory.new
  end

  # GET /tip_categories/1/edit
  def edit
  end

  def slug
    @tip_category = TipCategory.new name: params[:title]
    render json: { slug: @tip_category.slug_preview }
  end

  # POST /tip_categories
  # POST /tip_categories.json
  def create
    @tip_category = TipCategory.new(tip_category_params)

    respond_to do |format|
      if @tip_category.save
        format.html { redirect_to show_tip_category_path(@tip_category), notice: 'Tip category was successfully created.' }
        format.json { render :show, status: :created, location: @tip_category }
      else
        format.html { render :new }
        format.json { render json: @tip_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tip_categories/1
  # PATCH/PUT /tip_categories/1.json
  def update
    respond_to do |format|
      if @tip_category.update(tip_category_params)
        format.html { redirect_to show_tip_category_path(@tip_category), notice: 'Tip category was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip_category }
      else
        format.html { render :edit }
        format.json { render json: @tip_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tip_categories/1
  # DELETE /tip_categories/1.json
  def destroy
    @tip_category.destroy
    respond_to do |format|
      format.html { redirect_to tip_categories_url, notice: 'Tip category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def tip_category_params
    params.require(:tip_category).permit(:name, :description, :image, :slug)
  end
end

app/helpers/tip_categories_helper.rb
# @todo Перенсти это все в один хэлпер для категорий
module TipCategoriesHelper
  def nested_tip_categories(tip_categories)
    tip_categories.map do |tip_category, sub_tip_category|
      render(tip_category) + content_tag(:ul, nested_tip_categories(sub_tip_category), :class=> 'sub_tip_category')
    end.join.html_safe
  end

  def menu_tip_categories(tip_categories)
    tip_categories.map do |tip_category, sub_tip_category|
      content_tag(:li, link_to(tip_category.name, show_tip_category_path(tip_category)))
    end.join.html_safe
  end
end

app/views/tip_categories/_form.html.haml
= form_for @tip_category do |f|
  - if @tip_category.errors.any?
    #error_explanation
      %h1= "#{pluralize(@tip_category.errors.count, "error")} prohibited this tip_category from being saved:"
      %ul
        - @tip_category.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name, data: { url: slug_tip_categories_path }
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :description
    = f.text_area :description,:class => 'froala', :rows => 40, :cols => 120
  .field
    = image_tag @tip_category.image_url(:thumb_1200_630).to_s
    = f.label :image
    = f.file_field :image
    = f.check_box :remove_image

  .actions
    = f.submit 'Save'

app/views/tip_categories/_tip_category.html.haml
%li.tip_category
  .details
    %p.name= tip_category.name
    %p= truncate( tip_category.description, length: 200)
  .clear
  - if can? :tip_category, :update, :destroy
    .control
      = link_to t('edit'), edit_tip_category_path(tip_category)
      = link_to 'Destroy', tip_category, method: :delete, data: { confirm: 'Are you sure?' }

app/views/tip_categories/edit.html.haml
%h2 Editing tip_category

= render 'form'

= link_to 'Show', @tip_category
\|
= link_to 'Back', tip_categories_path

app/views/tip_categories/index.html.haml
.main-content
  .heading
  -if can? TipCategory, :create
    = link_to 'New Tip category', new_tip_category_path
  .clear
  %ul.tip_category_list
    - @tip_categories.all.each do |tip_category|
      = render tip_category
.clear

app/views/tip_categories/new.html.haml
%h1=t('newTipCategory')

= render 'form'

= link_to 'Back', tip_categories_path

app/views/tip_categories/show.html.haml
%p#notice= notice
.main-content{:itemscope => true, :itemtype => "http://schema.org/Article"}
  -content_for :for_head do
    /* general METAS
    %title #{@tip_category.name} | Dicas de Snowboard | Zona Radical
    %meta{:name => "description", :content =>  strip_tags(@tip_category.description.to_s)}
    /* facebook METAS
    %meta{:property=>"og:type", :content =>"article"}
    %meta{:property=>"og:description", :content =>   strip_tags(@tip_category.description.to_s)}
    %meta{:property=>"og:title", :content => t('tips') + ': ' + @tip_category.name + " | Zona Radical"}
    %meta{:property=>"og:url", :content => request.original_url.to_s}
    /* @Todo Make proper images for all resort categories
    %meta{:property=> "og:image", :content=> "https://zonaradical.com.br"+@tip_category.image_url(:thumb_1200_630)}
    /* schema.org METAS
    %meta{:itemprop=>"author", :content =>"Zona Radical"}
    %meta{:itemprop=>"url", :content => request.original_url.to_s}
  .heading{:itemprop=>"name"}
    %h1= t('tips') + ': ' + @tip_category.name
    %meta{:itemprop=>"name", :content => t('tips') + ': ' + @tip_category.name + " | Zona Radical"}
  .introtext
    = @tip_category.description.html_safe unless @tip_category.description.nil?
  -if can? :update, @tip_category
    = link_to t('edit'), edit_tip_category_path(@tip_category)
  .clear
  %ul.stations-list
    =render @tips
    = will_paginate @tips,:previous_label => '<<',:next_label => '>>', :inner_window => 1
-content_for :aside do
  %aside
    =render 'shared/aside/aside_social_buttons'
    =render 'shared/aside/aside_tip_category', :tip_category => @tip_category
    =render 'shared/aside/aside_fb_like_box'
    =render 'shared/aside/aside_resort_gallery'
    =render 'shared/aside/aside_advert'
  .clear