config/routes.rb
Rails.application.routes.draw do

  concern :sluggable do
    collection do
      get 'slug'
    end
  end

  namespace :api, defaults: {format: :json} do
    scope path: '/discourse_integration', as: :discourse do
      get 'top_menu', to: 'discourse_integration#top_menu', as: :top_menu
    end
  end

  resources :resorts, path: 'estacoes-ski-snowboard', concerns: :sluggable, except: :show
  get '/resorts/:id', to: 'resorts#resort_redirect', as: :resort_redirect
  get 'estacoes-ski-snowboard/:resort_category_id/:id', to: 'resorts#show', as: :show_resort

  get 'estacoes-ski-snowboard/:id', to: 'resort_categories#show', as: :show_resort_category
  resources :resort_categories, concerns: :sluggable, except: :show

  get '/resorts', to: redirect('/estacoes-ski-snowboard')
  get '/resort_categories/:id', to: redirect('/estacoes-ski-snowboard/%{id}')

  resources :tips, path: 'dicas', concerns: :sluggable, except: :show
  get '/tips/:id', to: 'tips#tip_redirect', as: :tip_redirect
  get 'dicas/:category_id/:id', to: 'tips#show', as: :show_tip

  get 'dicas/:id', to: 'tip_categories#show', as: :show_tip_category
  resources :tip_categories, concerns: :sluggable, except: :show

  get '/tips', to: redirect('/dicas')
  get '/tip_categories/:id', to: redirect('/dicas/%{id}')

  resources :videos, concerns: :sluggable, except: :show
  get 'videos/:category_id/:id', to: 'videos#show', as: :show_video

  get 'videos/:id', to: 'video_categories#show', as: :show_video_category
  resources :video_categories, concerns: :sluggable, except: :show

  resources :breezes, :breeze_categories
  resources :image_galleries, :media_image_categories

  resources :accommodations, :tour_styles
  resources :offers do
    get 'search', on: :collection
  end
  resources :tours, path: '/vamo-junto-snowboard' do
    get 'search', on: :collection
    post 'comment', on: :member
    scope module: 'tours' do
      resources :participants do
        get 'recall', on: :member
      end
    end
  end
  resources :offers, path: '/pacotes-snowboard' do
    scope module: 'offers' do
      resources :participants
    end
  end

  ActiveAdmin.routes(self)

  root 'static_pages#index'

  get '/galera', to: 'static_pages#galera', path: '/contatos'
  get '/friends', to: 'static_pages#friends', path: '/amigos'

  get 'users_controller/finish_signup'

  get '/discourse/sso', to: 'discourse#sso'
  get '/discourse/after_sign_in', to: 'discourse#after_sign_in'
  get '/discourse/logout', to: 'discourse#logout'

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  resources :users do
    scope module: 'users' do
      resources :tours
      resources :offers
    end
  end
  scope '/manage' do
    resources :users do
      resources :image_galleries
      resources :notifications
      patch 'update_password', on: :collection
      resources :tours, module: 'manage'
    end
  end
  namespace :manage do
    resources :tours do
      scope module: 'tours' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end
    resources :offers do
      scope module: 'offers' do
        resources :owners
        resources :participants do
          get :approve, :refuse, on: :member
        end
      end
    end
  end

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  match '/user' => 'users#profile', via: [:get], :as => :profile
  match '/user/full_sign_out' => 'users#full_sign_out', via: [:get], :as => :full_sign_out
  match '/athletes' => 'users#athletes', via: [:get], :as => :athletes, path: 'atletas-de-snowboard'
  match '/agencies' => 'users#agencies', via: [:get], :as => :agencies, path: 'agencias-ski-snowboard'
  match '/organizations' => 'users#organizations', via: [:get], :as => :organizations, path: 'ogranizacoes-de-snowboard'

  mount Forem::Engine, :at => '/forum', :as => 'forem'

  get '/galera', to: redirect('contatos')
  get '/friends', to: redirect('amigos')
  get '/tours', to: redirect('vamo-junto-snowboard')
  get '/athletes', to: redirect('atletas-de-snowboard')
  get '/agencies', to: redirect('agencias-ski-snowboard')
  get '/organizations', to: redirect('ogranizacoes-de-snowboard')

end

app/models/offer.rb
# create_table :offers, force: true do |t|
#   t.integer  :tour_style_id
#   t.integer  :accommodation_id
#   t.string   :title
#   t.text     :description
#   t.string   :whats_included
#   t.integer  :duration
#   t.integer  :check_in_d
#   t.integer  :check_in_m
#   t.integer  :check_in_y
#   t.integer  :switch_off_d
#   t.integer  :switch_off_m
#   t.integer  :switch_off_y
#   t.date     :check_in
#   t.date     :switch_off
#   t.string   :image
#   t.decimal  :price,            precision: 5, scale: 0
#   t.boolean  :published,                                default: true
#   t.datetime :created_at
#   t.datetime :updated_at
#   t.string   :hotel_name
#   t.boolean  :air_included
# end
#
# add_index :offers, [:accommodation_id], name: :index_offers_on_accommodation_id, using: :btree
# add_index :offers, [:tour_style_id], name: :index_offers_on_tour_style_id, using: :btree

class Offer < ActiveRecord::Base
  belongs_to :tour_style
  belongs_to :accommodation
  has_many :owners
  has_many :user_owners, through: :owners, source: :user
  has_many :participants
  has_many :user_participants, through: :participants, source: :user
  has_many :countries
  has_many :resort_categories, through: :countries
  has_many :offer_resorts
  has_many :resorts, through: :offer_resorts
  has_many :gallery_images, as: :gallerable

  validates :tour_style, :title, :description, presence: true
  validates :check_in_y, :check_in_m, presence: true
  validates :check_in_y, :check_in_m, numericality: { only_integer: true, greater_than: 0 }
  validate :country_presence
  validates :duration, presence: true

  mount_uploader :image, OfferImageUploader

  before_save do
    self.switch_off_d = check_in_d
    self.switch_off_m = check_in_m
    self.switch_off_y = check_in_y

    self.check_in = check_in_d.nil? ? Date.new(check_in_y, check_in_m) : Date.new(check_in_y, check_in_m, check_in_d)
    self.switch_off = switch_off_d.nil? ? Date.new(switch_off_y, switch_off_m) : Date.new(switch_off_y, switch_off_m, switch_off_d)
  end

  def approved_participants
    participants.where(status: Offer::Participant.statuses[:approved])
  end

  def self.published
    where(published: true)
  end

  def self.switched_on
    where("switch_off >= ?", Date.today)
  end

  def self.involved(user)
    includes([:user_owners, :user_participants])
      .where("offer_user_assignments.user_id = :user_id
        OR offer_user_participant_assignments.user_id = :user_id",
        user_id: user.id)
      .references([:user_owners, :user_participants])
  end

  def self.owned_by(users)
    includes(:user_owners).where(
      offer_user_assignments: { user_id: users.collect(&:id) }
    )
  end

  def self.filter(options = {})
    offers = where(nil)
    offers = offers.includes(:resort_categories).where(resort_categories: { id: options['resort_categories'] }) if options['resort_categories']
    offers = offers.where(check_in_m: options['check_in_m'], check_in_y: options['check_in_y']) if options['check_in_m'] and options['check_in_y']
    offers = offers.where(tour_style: options['tour_style']) if options['tour_style']
    offers = offers.where(accommodation: options['accommodation']) if options['accommodation']
    offers = offers.where(price: options['cost']) if options['cost']
    if options['age_group']
      offers = offers.includes(:user_owners)
        .where(offer_user_assignments: { id: Tour::Owner.first_owners_by_tour })
        .where(users: { birthday: options['age_group'] })
    end
    offers = offers.includes(:resorts).where(resorts: { id: options['resorts'] }) if options['resorts']
    offers = offers.switched_on if options['show_passed'] != "1"
    offers
  end

  private

  def self.use_relative_model_naming?
    true
  end

  def country_presence
    errors.add(:base, :missing_country) if self.countries.empty?
  end
end

app/models/offer/country.rb
# create_table :offer_country_assignments, force: true do |t|
#   t.integer :offer_id
#   t.integer :resort_category_id
# end
#
# add_index :offer_country_assignments, [:offer_id], name: :index_offer_country_assignments_on_offer_id, using: :btree
# add_index :offer_country_assignments, [:resort_category_id], name: :index_offer_country_assignments_on_resort_category_id, using: :btree

class Offer::Country < ActiveRecord::Base
  self.table_name = 'offer_country_assignments'

  belongs_to :offer
  belongs_to :resort_category
end

app/models/offer/offer_resort.rb
# create_table :offer_resort_assignments, force: true do |t|
#   t.integer :offer_id
#   t.integer :resort_id
# end
#
# add_index :offer_resort_assignments, [:offer_id], name: :index_offer_resort_assignments_on_offer_id, using: :btree
# add_index :offer_resort_assignments, [:resort_id], name: :index_offer_resort_assignments_on_resort_id, using: :btree

class Offer::OfferResort < ActiveRecord::Base
  self.table_name = 'offer_resort_assignments'

  belongs_to :offer
  belongs_to :resort
end

app/models/offer/owner.rb
# create_table :offer_user_assignments, force: true do |t|
#   t.integer :offer_id
#   t.integer :user_id
# end
#
# add_index :offer_user_assignments, [:offer_id], name: :index_offer_user_assignments_on_offer_id, using: :btree
# add_index :offer_user_assignments, [:user_id], name: :index_offer_user_assignments_on_user_id, using: :btree

class Offer::Owner < ActiveRecord::Base
  self.table_name = 'offer_user_assignments'

  belongs_to :offer
  belongs_to :user

  def self.first_owners_by_tour
    Offer::Owner.where(id: Offer::Owner.group(:tour_id).minimum(:id).values)
  end
end

app/models/offer/participant.rb
# create_table :offer_user_participant_assignments, force: true do |t|
#   t.integer :offer_id
#   t.integer :user_id
#   t.integer :status,   default: 0
# end
#
# add_index :offer_user_participant_assignments, [:offer_id], name: :index_offer_user_participant_assignments_on_offer_id, using: :btree
# add_index :offer_user_participant_assignments, [:user_id], name: :index_offer_user_participant_assignments_on_user_id, using: :btree

class Offer::Participant < ActiveRecord::Base
  self.table_name = 'offer_user_participant_assignments'

  belongs_to :offer
  belongs_to :user
  enum status: [:pending, :approved, :refused]

  validates :user_id, uniqueness: { scope: :offer_id }

  delegate :url_helpers, to: 'Rails.application.routes'
  delegate :helpers, to: 'ActionController::Base'

  def approve
    user.notify('Solicitação aprovada', "Sua participação na offer '#{offer.title}' foi aprovada.") if approved!
  end

  def refuse
    user.notify('Solicitação recusada', "Sua participação na offer '#{offer.title}' foi recusada.") if refused!
  end
end

app/controllers/offers/participants_controller.rb
class Offers::ParticipantsController < ApplicationController
  load_resource :offer
  load_and_authorize_resource :participant, through: :offer, class: Offer::Participant

  def create
    build_participant
    save_participant or redirect_to offers_path, notice: 'Não foi possível completar a operação.'
  end

  private

  def build_participant
    @participant ||= participant_scope.build
    @participant.attributes = participant_params
  end

  def save_participant
    if @participant.save
      url = manage_offer_participants_url(@offer)
      @offer.owners.first.user.notify("Solicitação para participação em offer",
        "O usuário '#{current_user.name}' gostaria de participar da offer '#{@offer.title}'.
         Para avaliar este pedido acesse #{view_context.link_to url, url}.")
      redirect_to offer_path(@offer), notice: 'Seu pedido foi enviado, em breve você receberá uma resposta.'
    end
  end

  def participant_params
    participant_params = params[:participant]
    participant_params ? participant_params.permit(:offer_id, :user_id) : {}
  end

  def participant_scope
    @offer.participants
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    load_offers
  end

  def show
    load_offer
  end

  def search
    load_filtered_offers
    render 'index'
  end

  def offers
    load_offers
  end

  private

  def load_offers
    @offers ||= offer_scope.switched_on.paginate(page: params[:page]).to_a
  end

  def load_offer
    @offer ||= offer_scope.find(params[:id])
  end

  def load_filtered_offers
    filter_options = search_params.delete_if { |k,v| v == "" }

    if filter_options['period']
      check_in_m, check_in_y = filter_options['period'].split('/')
      filter_options['check_in_m'] = check_in_m.to_i
      filter_options['check_in_y'] = check_in_y.to_i
      filter_options.delete('period')
    end
    
    if filter_options['cost']
      cost = filter_options['cost']
      cost = Range.new(*cost.split('..').map { |n| BigDecimal(n).to_f })
      filter_options['cost'] = cost
    end
    
    if filter_options['age_group']
      age_group = filter_options['age_group']
      age_group = Range.new(*age_group.split('..').map { |d| Date.parse(d) })
      filter_options['age_group'] = age_group
    end

    @offers ||= offer_scope.filter(filter_options).paginate(page: params[:page]).to_a
  end

  def search_params
    params.require(:search).permit(:resort_categories, :period, :tour_style,
      :accommodation, :cost, :age_group, :resorts, :show_passed)
  end

  def offer_scope
    Offer.published.order(:check_in)
  end
end

app/controllers/users/offers_controller.rb
class Users::OffersController < ApplicationController
  load_resource :user

  def index
    load_offers
  end

  private

  def load_offers
    offers_query = params[:show_passed].nil? ? tour_scope.switched_on : tour_scope
    @offers_owned = offers_query.owned_by([@user]).to_a
  end

  def tour_scope
    Offer.published.involved(@user)
  end
end

app/helpers/offers_helper.rb
module OffersHelper
  def offer_participation_status(offer, options = {})
    participate_button = options[:participate_button] || false

    if offer.user_participants.include?(current_user)
      if offer.participants.where(user: current_user).first.approved?
        fa_icon('check-circle', text: t('youAreIn'), class: 'green')
      elsif offer.participants.where(user: current_user).first.refused?
        fa_icon('times-circle', text: t('participationRefused'), class: 'red')
      else
        fa_icon('question-circle', text: t('participationRequestSent'), class: 'yellow')
      end
    elsif participate_button
      form_for [offer, Offer::Participant.new] do |f|
        concat(f.hidden_field :offer_id, value: offer.id)
        concat(f.hidden_field :user_id, value: current_user.id)
        concat(f.submit t('participate'))
      end if current_user and not offer.user_owners.include?(current_user)
    end
  end

  def offer_resort_categories
    Offer.published.collect(&:resort_categories).flatten.uniq.reject { |item| item.blank? }
  end

  def offer_dates
    Offer.published.collect { |t| Date.new(t.check_in_y, t.check_in_m) }.uniq.sort
  end

  def offer_styles
    Offer.published.collect(&:tour_style).uniq
  end

  def offer_accommodations
    Offer.published.collect(&:accommodation).uniq.reject { |item| item.blank? }
  end

  def offer_resorts
    Offer.published.collect(&:resorts).flatten.uniq.reject { |item| item.blank? }
  end

  def check_in_formatted(offer)
    if offer.check_in_d.nil?
      offer.check_in.strftime('%m/%Y')
    else
      offer.check_in.strftime('%d/%m/%Y')
    end
  end

  def offer_countries(offer)
    offer.resort_categories.collect(&:name).join(', ')
  end

  def offer_resorts_names(offer)
    offer.resorts.collect(&:name).join(', ')
  end

  def offer_resorts_names_linked(offer)
    offer.resorts.collect do |resort|
      link_to resort.name, show_resort_path(resort.resort_category, resort), target: '_blank'
    end.join(', ').html_safe
  end
end

app/views/offers/_list.html.haml
%ol.announcement-list
  - offers.each do |offer|
    %li
      %p{:style=>"float: right;"}
        - if offer.user_owners.include?(current_user)
          Seu pacote
        - else
          - offer.user_owners.each do |onwr|
            = avatar_img_sm(onwr)
            = link_to onwr.surname[0..12]+"...", onwr, target: '_blank'
      %p.title
        = link_to offer.title, send(offer_path_method, offer)
        / = participation_status(offer)
      %i.date
        %span{:title=>t('check_in')}
          = check_in_formatted(offer)
        %span{:title=>"Paises de destino"}
          %b= offer.resort_categories.collect(&:name).join(', ')
        %span{:title=>"Estações de destino"}
        = tour_resorts_names(offer)
        %br
        r$
        =offer.price
      %p= truncate_html(offer.description.html_safe, length: 100)
      = link_to 'Leia mais', send(offer_path_method, offer), class: 'read-more'
      - if can? :manage, offer
        %br
        = link_to t('edit'), edit_manage_offer_path(offer)
        / |
        / = link_to t('participants'), manage_offer_participants_path(offer)
        |
        = link_to t('destroy'), manage_offer_path(offer), method: :delete, data: { confirm: t('confirm_destroy') }
/ end announcement-list/ end announcement-list

app/views/offers/_show.html.haml
.tour-card
  .leftcol
    = tour_logo_img(@offer)
    %ul.details-list
      %li.contacts
        .contacts-list
          %span.map{:title=> t('countries')}
            = offer_countries(@offer)
  .rightcol
    .h2
      /* %span.name
      %b{:title=>"Estacoes"}
        = offer_resorts_names_linked(@offer)
    %ul.details-list
      %li.details
        .details-list
          %span.date{:title=> t('check_in')}
            = check_in_formatted(@offer)
          -unless @offer.duration.nil?
            %span.days{:title=> t('duration')}
              = @offer.duration
              dias
          -unless @offer.price.nil?
            %span.price{:title=> t('price')}
              R$
              = @offer.price
              por pessoa
          -unless !@offer.air_included
            %span.air
              A passagem aérea está inclusa
          %span.style{:title=> t('tourStyle')}
            = @offer.tour_style
          %span.accom{:title=> t('accommodation')}
            = @offer.accommodation

        .clear
  .h2{:itemprop=>"name"}
    Agência
  .parti-col
    .ava-col
      = avatar_img_sm(@offer.user_owners.first)
    .name-col
      = link_to @offer.user_owners.first.surname, @offer.user_owners.first, target: '_blank'
  .clear
  %div{:style=>"text-align: center; margin-bottom: 10px;"}
    %i
      Entra em contato com a Agência
      = @offer.user_owners.first.surname
      =link_to @offer.user_owners.first.email,"mailto:"+@offer.user_owners.first.email.to_s+"?subject= pacote publicado no ZR"

  -unless @offer.description.nil?
    %p.descr
      %b
        =t('description')
        \:
      = @offer.description.html_safe
  / - unless @offer.participants_in([:pending, :approved]).empty?
  /   %p.descr
  /     %b
  /       =t('participants')
  /     %ul
  /       - @offer.participants_in([:pending, :approved]).each do |participant|
  /         %li== #{participant.user.name} #{participant.user.surname}
  /     - if @offer.participants_in([:pending]).where(user: current_user).first
  /       - tour_participant = @offer.participants_in([:pending]).where(user: current_user).first
  /       = link_to 'Recall', recall_tour_participant_path(@offer, tour_participant), class: 'button'
  %p.small
    %b
      Estilos de trip:
    -TourStyle.all.each do |t_style|
      = t_style.name
      ="("+t_style.description.to_s+")."
    %b
      Tipos de moradia:
    -Accommodation.all.each do |acco|
      = acco.name
      ="("+ acco.description.to_s+")."
  %div{:style=>"text-align: center"}
  -unless @offer.gallery_images.all.count.zero?
    = render 'shared/sliders/tip', images: @offer.gallery_images.all



/*  - @offer.resorts.each do |resort|
/*    = resort_logo_img(resort)

/ = participation_status(@offer, participate_button: true)

app/views/offers/index.html.haml
.main-content
  -content_for :for_head do
    /* general METAS
    %title Pacotes de Snow | Zona Radical
    %meta{:name => "description", :content =>  "Todos os pacotes de vigem de neve num site so. E aqui. Encontre sua viagem de snowboard prefeita!"}
    %meta{:property=>"og:type", :content =>"article"}
    %meta{:property=>"og:title", :content => "Pacotes de Snow | Zona Radical" }
    %meta{:property=>"og:url", :content => request.original_url.to_s}
    %meta{:property=> "og:image", :content=> "http://zonaradical.com.br/images/vamo_junto1.png"}
  .heading
    %h1
      Pacotes turisticos
    .fb-like{"data-href"=> request.original_url.to_s, "data-layout"=>"button", "data-action"=>"like", "data-show-faces"=>"true", "data-share"=>"true", :style => "float: right;"}
  %p.search-intro{:style => "margin-bottom: 0px;"}
    Aqui você pode encontrar os pacotes de viagens para praticar snowboard e ski oferecidos no Brasil.
    %br
    Não são os pacotes do ZR, nos não estamos vendendo nada. São das agêcias turísticas brasileiras, a lista dessas ultimas está aqui:
    = link_to "Agências de neve", main_app.agencies_path

  -if !mobile_device?
    - if can? :manage, Offer
      = link_to 'Adicionar um pacote', new_manage_offer_path, class: 'button', :style=>"display: block; margin-left: auto; margin-right: auto; margin-top: 5px;margin-bottom: 5px;"
    = form_for :search, url: search_offers_path, method: :get do |f|
      %p.small
        Escolha os parâmetros abaixo para encontrar um pacote do seu jeito, do seu gosto.
      .search-filter
        .select-wrap
          = f.hidden_field :resort_categories, value: search_value_for(:resort_categories)
          .select
            %span.name País(es)
            %a.arrow{:href => "#"}
          %ul.option-list
            %li.default{data: {value: ''}} Tanto faz
            - offer_resort_categories.each do |resort_category|
              %li{data: { value: resort_category.id }}= resort_category.name
        .select-wrap
          = f.hidden_field :resorts, value: search_value_for(:resorts)
          .select
            %span.name Estação
            %a.arrow{:href => "#"}
          %ul.option-list
            %li.default{data: {value: ''}} Tanto faz
            - offer_resorts.each do |resort|
              %li{data: { value: resort.id, category_id: resort.resort_category_id } }= resort.name
        .select-wrap
          = f.hidden_field :period, value: search_value_for(:period)
          .select
            %span.name Periodo
            %a.arrow{:href => "#"}
          %ul.option-list
            %li.default{data: {value: ''}} Todos
            - offer_dates.each do |date|
              %li{data: { value: date.strftime("%m/%Y") }}= date.strftime("%B'%y")
        .select-wrap
          = f.hidden_field :tour_style, value: search_value_for(:tour_style)
          .select
            %span.name Alvo
            %a.arrow{:href => "#"}
          %ul.option-list
            %li.default{data: {value: ''}} Tanto faz
            - offer_styles.each do |offer_style|
              %li{data: { value: offer_style.id }}= offer_style.name
        .select-wrap
          = f.hidden_field :accommodation, value: search_value_for(:accommodation)
          .select
            %span.name Hospedagem
            %a.arrow{:href => "#"}
          %ul.option-list
            %li.default{data: {value: ''}} Todos tipos
            - offer_accommodations.each do |accommodation|
              %li{data: { value: accommodation.id }}= accommodation.name
        .select-wrap
          = f.hidden_field :cost, value: search_value_for(:cost)
          .select
            %span.name Custos
            %a.arrow{:href => "#"}
          %ul.option-list
            %li.default{data: {value: ''}} Qualquer
            %li{"data-value" => "0..499"} menos de r$ 500 por pessoa
            %li{"data-value" => "500..1000"} r$ 500 - r$ 1000
            %li{"data-value" => "1000..Infinity"} mais de r$ 1000 por pessoa
        .select-extra
        /.select-wrap
        /  = f.hidden_field :age_group, value: search_value_for(:age_group)
        /  .select
        /    %span.name Faixa etaria preferida
        /    %a.arrow{:href => "#"}
        /  %ul.option-list
        /    %li.default{data: {value: ''}} Tanto faz
        /    %li{"data-value" => "#{18.years.ago.to_date}..#{Date.today}"} menos de 18
        /    %li{"data-value" => "#{25.years.ago.to_date}..#{18.years.ago.to_date}"} 18-25
        /    %li{"data-value" => "#{99.years.ago.to_date}..#{25.years.ago.to_date}"} 25-99
        .select-extra
          = f.submit t('applyFilters'), :style=>"display: block; margin-left: auto; margin-right: auto;"
        .select-extra
          - if action_name == 'search'
            = link_to t('cleanFilters'), main_app.offers_path, class: 'button', style: "display: block; margin-left: auto; margin-right: auto;"

        .clear
      / end search-filter

    / :style=>"float: right;"
    .heading
      - if action_name == 'search'
        %h1 Pacotes filtrados
      - else
        %h1 Todos os pacotes
      - if can? :manage, Offer
        = link_to 'Os meus pacotes', manage_offers_path, class: 'all my-ads', target: '_blank'
  - else
    Para publicar um pacote ou aplicar filtros nos anuncios publicados por favor usa a versão desktop do site.
    .heading
      %h1 Todos os anúncios

  - if @offers.empty?
    Não existem pacotes ou nenhum foi encontrada com os filtros especificados.
  - else
    = render 'list', offers: @offers, offer_path_method: "offer_path"
    = will_paginate @offers
  .clear

  -content_for :aside do
    %aside
      =render 'shared/aside/aside_social_buttons'
      /=render 'shared/aside/aside_tip_category', :tip_category => nil
      =render 'shared/aside/aside_fb_like_box'
      =render 'shared/aside/aside_advert'
      =render 'shared/aside/aside_resort_gallery'
    .clear

app/views/offers/show.html.haml
.main-content
  -content_for :for_head do
    /* general METAS
    %title #{@offer.title} | Pacote de Snow com Zona Radical
    %meta{:name => "description", :content =>  strip_tags(@offer.description.to_s)}

    /* facebook METAS
    %meta{:property=>"og:type", :content =>"article"}
    %meta{:property=> "og:description", :content =>   strip_tags(@offer.description.to_s)}
    %meta{:property=>"og:title", :content => "Pacote de Snow: " +@offer.title}
    %meta{:property=>"og:url", :content => request.original_url.to_s}
    - if @offer.gallery_images.all.count.zero?
      %meta{:property=> "og:image", :content=> "http://zonaradical.com.br/images/vamo_junto.png"}
      %meta{:itemprop=> "photo", :content=> "http://zonaradical.com.br/images/vamo_junto.png"}
    - else
      -@offer.gallery_images[0..3].each do |image|
        %meta{:property=> "og:image", :content=> image.image_url(:slider).to_s}
        %meta{:itemprop=> "photo", :content=> image.image_url(:slider).to_s}
    /* schema.org METAS
    /* %meta{:itemprop=>"location", :content => @resort.resort_category.name.to_s}
    %meta{:itemprop=>"url", :content => request.original_url.to_s}
  .heading
    %h1
      Offer:
      = @offer.title

  %article
    = render 'show'

    .clear

    - if can? :manage, @offer
      = link_to 'Edit', edit_manage_offer_path(@offer)
      \|
    = link_to 'Back', offers_path

-content_for :aside do
  %aside
    =render 'shared/aside/aside_social_buttons'
    =render 'shared/aside/aside_advert'
    =render 'shared/aside/aside_fb_like_box'
    =render 'shared/aside/aside_resort_gallery'
  .clear